### ISSUE TITLE
Opened Browser is not being foregrounded

### ISSUE THREAD

**Issue by tallen1983** [aloneguid/bt#39] opened 2023-08-31 13:32 UTC
When Browser Tamer decides it should open a link in Chrome's ProfileX, instead of that browser window being foregrounded, it just flashes in my task bar in the background. This happens if I have Chrome's ProfileX already open or not.

When not using Browser Tamer the browser is opened and foregrounded, so the expectation is it would work the same.

As it currently stands this makes Browser tamer only slightly easier to use than what I was previously doing (before clicking a particular link making sure I click the proper Chrome icon in my taskbar first to activate that profile).

**Comment by aloneguid** [comment] 2023-09-02 20:01
Unfortunately this is up to a browser whether to foreground a window or not and has nothing to do with BT. Its tricky to find a correct foreground window if I would to try to implement a workaround as Chrome can have multiple windows for the same profile open and multiple profiles too. I could probably search taskbar for a flashing window and activate that but it needs a bit of experimentation as it's easy to do it very wrong.

**Comment by tallen1983** [comment] 2023-09-05 14:52
Thanks @aloneguid 

I find it very odd that chrome behaves differently if you ask it to open a link compared to if windows does directly.
I get it, it's a slightly different code path for them (chrome open this link and it decides what the last active window was vs chrome open this link inside this profile). But I'm wondering if there is some other magic that windows does that causes the window to come to the forefront (different API to launch it, etc).

**Comment by aloneguid** [comment] 2023-09-07 15:34
I think this is resolved in 3.5.2.

**Comment by mahoromax** [comment] 2023-09-09 02:15
No, it sadly is not :(
I made sure I have 3.5.2 but things still open in the background.

Firefox and Edge behave differently, although I did not test them with multiple profiles.

**Comment by paz** [comment] 2023-09-10 04:50
3.5.2 fixed this issue for me

**Comment by aloneguid** [comment] 2024-01-26 15:33
I will try a few things, it could be related to the fact that BT is not in foreground when links are opened, not quite sure.

**Comment by mahoromax** [comment] 2024-01-26 22:52
I haven't actively exp'd this for a while, maybe I got used to it. I will try to observe and add in an edit.

**Comment by aloneguid** [comment] 2024-02-01 11:08
Please try 3.7.1, this has worked for me. I think the issue is BT is disposing process handles too early, and that's only reproducible in the release mode.

**Comment by s-a-m** [comment] 2024-02-24 12:27
This is still happening in 3.7.3. It seems related to BT being in the foreground or minimized in the icon tray. That is, opening it up, helps links go in the foreground, while closing it up, sends links to the background by default. I'm using process rules and Firefox Developer Edition.

**Comment by aloneguid** [comment] 2024-07-15 11:40
This should not be an issue anymore since v4.

**Closed by aloneguid** 2024-07-15 11:40 UTC
Labels: core
